# Generated by Django 6.0.4 on 2026-05-05 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('election', 'voter_token')},
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
    ]
